# Generated by Django 3.1.2 on 2020-11-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_place_information_end_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='place_information',
        ),
    ]
