# Generated by Django 2.2.10 on 2021-09-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures'),
        ),
    ]
