# Generated by Django 2.2.10 on 2021-09-29 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210929_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designatioin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='member_since',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
