# Generated by Django 2.2.10 on 2021-09-29 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210929_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='member_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
