# Generated by Django 2.2.10 on 2021-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210929_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(default='A place where a character builts.', max_length=255),
        ),
    ]
