# Generated by Django 2.2.10 on 2021-09-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_company_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.ImageField(upload_to='temp_folder')),
            ],
        ),
    ]
